# [terminal]
# shell = { program = "C:\\Windows\\System32\\wsl.exe", args = ["~"] }
# WSL Users (Windows)

[window]
padding = { x = 15, y = 15 }
opacity = 0.85
position = {x=560,y=240} #Startup Position
decorations = "Buttonless"

[scrolling]
history = 10000
multiplier = 3 

[font]
size = 18

[cursor]
style = "Block"
blink_interval = 500

[colors.primary]
background = "#000000"  
foreground = "#ff8c00"  

[colors.normal]
black   = "#121212"
red     = "#ff0044"
green   = "#00ff66"
yellow  = "#ffcc00"
blue    = "#00b3ff"
magenta = "#ff00ff"
cyan    = "#00ffff"
white   = "#cccccc"

[colors.bright]
black   = "#333333"
red     = "#ff6666"
green   = "#66ff99"
yellow  = "#ffcc66"
blue    = "#66ccff"
magenta = "#ff66ff"
cyan    = "#66ffff"
white   = "#ffffff"

[keyboard]
# Use Control For Windows Users 
bindings = [
    # Copy to clipboard (Cmd + Shift + C)
    { key = "C", mods = "Super|Shift", action = "Copy" },

    # Paste from clipboard (Cmd + Shift + V)
    { key = "V", mods = "Super|Shift", action = "Paste" },

    # Paste from clipboard (Cmd + V) - Additional binding
    { key = "V", mods = "Super", action = "Paste" },

    # Quit Alacritty (Cmd + Shift + Q)
    { key = "Q", mods = "Super|Shift", action = "Quit" },

    # Open a new window (Cmd + Shift + N)
    { key = "N", mods = "Super|Shift", action = "SpawnNewInstance" },

    # Toggle fullscreen (F11)
    { key = "F11", action = "ToggleFullscreen" },

    # Scroll up (Cmd + Shift + Up Arrow)
    { key = "Up", mods = "Super|Shift", action = "ScrollPageUp" },

    # Scroll down (Cmd + Shift + Down Arrow)
    { key = "Down", mods = "Super|Shift", action = "ScrollPageDown" },
 
    # Increase Font Size (Cmd + Plus)
    { key = "Plus", mods = "Super", action = "IncreaseFontSize" },

    # Decrease Font Size (Cmd + Minus)
    { key = "Minus", mods = "Super", action = "DecreaseFontSize" },
    
    # Quit Alacritty (Cmd + Q)
    { key = "Q", mods = "Super", action = "Quit" },

    # Quit Alacritty (Cmd + X)
    { key = "X", mods = "Super", action = "Quit" },

    # Toggle Fullscreen (Cmd + Shift + F)
    { key = "F", mods = "Super|Shift", action = "ToggleFullscreen" }
]

[mouse]
bindings = [
    { mouse = "Right", action = "Paste" }
]
